version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: traceflow-mysql  # 必须和脚本一致
    restart: always
    ports:
      - '3307:3306'                # 端口和你.env一致
    environment:
      MYSQL_ROOT_PASSWORD: 123456   # 密码 = 你.env的 123456
      MYSQL_DATABASE: traceflow     # 库名 = 你.env的 traceflow
      MYSQL_USER: tracker
      MYSQL_PASSWORD: tracker123
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - tracker-network

  redis:
    image: redis:alpine
    container_name: tracker-redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    networks:
      - tracker-network

networks:
  tracker-network:
    driver: bridge

volumes:
  mysql-data:
  redis-data: